name: pre-commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  repository_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: 3.13
    - name: pre-commit
      uses: pre-commit/action@v3.0.1
